# Generated by Django 2.2.7 on 2019-11-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userName', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
                ('userRole', models.CharField(max_length=15)),
            ],
        ),
    ]
